
server:
  port: 9000

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 19314152
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
#mybatis
mybatis:
  #数据库的映射文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

domain:
  url: "http://localhost:9000/uploadimg/"
